Improve test coverage on AppVeyor (#3328)
In this PR we adjust AppVeyor builds to 
- enable `pyarrow` tests;
- on Windows, enable C++ tests by testing debug wheels for Python 3.9;
- on Windows, fix builds to properly report failures;
- for consistency, rename `DTTEST` to `DT_TEST` and namespace `dttest` to `dt::tests`.

Note, that, when enabled, the C++ tests [redefine](https://github.com/h2oai/datatable/blob/main/src/core/utils/tests.h#L91-L100) `protected` and `private` keywords to `public`. This is a pretty dangerous approach, that we might need to reconsider, because this redefinition only happens in the files which include `utils/tests.h`. On Windows, for instance, this caused a pile of linking errors due to the fact that some methods were expected to be `public`, but were declared as `protected` or `private`.

diff --git a/ci/appveyor.yml b/ci/appveyor.yml
--- a/ci/appveyor.yml
+++ b/ci/appveyor.yml
@@ -21,10 +21,12 @@ artifacts:
 environment:
   APPVEYOR_YML_DISABLE_PS_LINUX: true
 
+matrix:
+  fast_finish: true
 
 build_script:
 
-# Linux and macOS builds
+# Linux and macOS builds.
 - sh: >-
 
     # =======================================================================
@@ -99,18 +101,32 @@ build_script:
 
     python -m pip install --upgrade pip
 
-    python -m pip install $DT_WHEEL pytest docutils pandas
+    python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
 
     python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
 
 
 
-# Windows builds
+# Windows builds.
+#
+# We use PowerShell that has more powerful syntax
+# than the standard command prompt. Unfortunately, PowerShell only takes
+# into account exit code of the last command and, if other commands fail,
+# the build can still be marked as green. Partially this problem is solved
+# by setting `$ErrorActionPreference` to `"Stop"`, that works well with
+# cmdlets. However, ultimately every PowerShell command should be followed
+# by the check `if(!$?) { Exit $LASTEXITCODE }`, that will stop the build
+# on the first failed command. Since we don't want to make the code too
+# cumbersome, here we only check the exit status of `pytest` that is still
+# a pretty good indicator.
+
 - ps: >-
 
     # =======================================================================
     #   Set up environment variables
     # =======================================================================
+
+    $ErrorActionPreference = "Stop"
 
     $env:DT_HARNESS = "AppVeyor"
 
@@ -178,7 +194,7 @@ build_script:
 
       python ci/ext.py wheel
 
-      $DT_WHEEL = ls dist/*-cp37-*.whl
+      $DT_WHEEL = ls dist/*$env:DT_BUILD_SUFFIX-cp37-*.whl
 
       echo "----- _build_info.py for Python 3.7 ------------------------------"
 
@@ -188,9 +204,13 @@ build_script:
 
       python -m pip install --upgrade pip
 
-      python -m pip install $DT_WHEEL pytest docutils pandas
+      python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
 
       python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
+
+      if(!$?) { Exit $LASTEXITCODE }
+
+      python -m pip uninstall -y $DT_WHEEL
 
     }
 
@@ -206,7 +226,7 @@ build_script:
 
     python ci/ext.py wheel
 
-    $DT_WHEEL = ls dist/*-cp38-*.whl
+    $DT_WHEEL = ls dist/*$env:DT_BUILD_SUFFIX-cp38-*.whl
 
     echo "----- _build_info.py for Python 3.8 ------------------------------"
 
@@ -216,9 +236,43 @@ build_script:
 
     python -m pip install --upgrade pip
 
-    python -m pip install $DT_WHEEL pytest docutils pandas
+    python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
 
     python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
+
+    if(!$?) { Exit $LASTEXITCODE }
+
+    python -m pip uninstall -y $DT_WHEEL
+
+
+
+    # =======================================================================
+    #   Build and test debug wheel for Python 3.9
+    # =======================================================================
+
+    $env:PATH = "C:/Python39-x64;C:/Python39-x64/Scripts;$DEFAULT_PATH"
+
+    python -V
+
+    python ci/ext.py debugwheel
+
+    $DT_WHEEL = ls dist/*$env:DT_BUILD_SUFFIX.debug-cp39-*.whl
+
+    echo "----- _build_info.py for Python 3.9 debug wheel ------------------"
+
+    cat src/datatable/_build_info.py
+
+    echo "------------------------------------------------------------------"
+
+    python -m pip install --upgrade pip
+
+    python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
+
+    python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
+
+    if(!$?) { Exit $LASTEXITCODE }
+
+    python -m pip uninstall -y $DT_WHEEL
 
 
 
@@ -232,7 +286,7 @@ build_script:
 
     python ci/ext.py wheel
 
-    $DT_WHEEL = ls dist/*-cp39-*.whl
+    $DT_WHEEL = ls dist/*$env:DT_BUILD_SUFFIX-cp39-*.whl
 
     echo "----- _build_info.py for Python 3.9 ------------------------------"
 
@@ -242,9 +296,13 @@ build_script:
 
     python -m pip install --upgrade pip
 
-    python -m pip install $DT_WHEEL pytest docutils pandas
+    python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
 
     python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
+
+    if(!$?) { Exit $LASTEXITCODE }
+
+    python -m pip uninstall -y $DT_WHEEL
 
 
 
@@ -258,7 +316,7 @@ build_script:
 
     python ci/ext.py wheel
 
-    $DT_WHEEL = ls dist/*-cp310-*.whl
+    $DT_WHEEL = ls dist/*$env:DT_BUILD_SUFFIX-cp310-*.whl
 
     echo "----- _build_info.py for Python 3.10 ------------------------------"
 
@@ -268,6 +326,11 @@ build_script:
 
     python -m pip install --upgrade pip
 
-    python -m pip install $DT_WHEEL pytest docutils pandas
+    python -m pip install $DT_WHEEL pytest docutils pandas pyarrow
 
     python -m pytest -ra --maxfail=10 -Werror -vv --showlocals ./tests/
+
+    if(!$?) { Exit $LASTEXITCODE }
+
+    python -m pip uninstall -y $DT_WHEEL
+
